#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y +=  mt6592/dummy_lens/
#obj-y +=  mt6592/bu6424af/
# obj-y += sensordriver/sensordrive_lens.o

